name: gh-pages publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          npm run build
      - name: upload
        uses: actions/upload-artifact@v2.2.3
        with:
          name: dist
          path: dist/
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download
        uses: actions/download-artifact@v2.0.9
        with:
          name: dist
          path: dist/
      - name: publish
        uses: Cecilapp/GitHub-Pages-deploy@3.1.0
        with:
          build_dir: dist/
  
